// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv9fweC_g87kaalI1l4trzr-fry81tVjY',
    appId: '1:390581366437:web:626093fee5be007c61674c',
    messagingSenderId: '390581366437',
    projectId: 'ebayan-4ebc1',
    authDomain: 'ebayan-4ebc1.firebaseapp.com',
    storageBucket: 'ebayan-4ebc1.appspot.com',
    measurementId: 'G-9ZR3FEYDG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wcsvKbfFravwftvcgqdEballB9Xe10s',
    appId: '1:390581366437:android:a7585fed8c2c60c461674c',
    messagingSenderId: '390581366437',
    projectId: 'ebayan-4ebc1',
    storageBucket: 'ebayan-4ebc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7m9uJ5TgCsRbncSG9hZgopXKvvbbl9ho',
    appId: '1:390581366437:ios:dfc036e6bcaccac361674c',
    messagingSenderId: '390581366437',
    projectId: 'ebayan-4ebc1',
    storageBucket: 'ebayan-4ebc1.appspot.com',
    iosBundleId: 'com.example.ebayan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7m9uJ5TgCsRbncSG9hZgopXKvvbbl9ho',
    appId: '1:390581366437:ios:9a54103b31822da761674c',
    messagingSenderId: '390581366437',
    projectId: 'ebayan-4ebc1',
    storageBucket: 'ebayan-4ebc1.appspot.com',
    iosBundleId: 'com.example.ebayan.RunnerTests',
  );
}
